[project]
name = "neural-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keras>=3.15.1",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "opencv-python>=5.0.0.93",
    "scikit-learn>=1.9.0",
    "tensorflow>=2.21.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.5",
    "yapf>=0.43.0",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG001", # unused arguments in functions
    "T201",   # print statements are not allowed
]
ignore = [
    "E501",  # line too long, handled by black
    "E701",  # multiple statements on one line (colon)
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "B904",  # allow raising exceptions without from e, for HTTPException
    "T201",  # allow print statements, for testing purposes
    "DTZ005",  # allow using datetime.now() without timezone, for testing purposes
]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"] # ignore unused imports in __init__.py files

[tool.yapf]
based_on_style = "pep8"
column_limit = 120
dedent_closing_brackets = true
disable_split_list_with_comment = false
spaces_before_comment = 4
split_all_comma_separated_values = false
split_arguments_when_comma_terminated = false
split_before_first_argument = true
split_before_logical_operator = true
split_complex_comprehension = true

[tool.yapfignore]
ignore_patterns = [
    ".venv/**",
    "build/**",
    "dist/**",
    "alembic/**",
]
